### ISSUE TITLE
Setup Restart Squad Server Action to a schedule

### ISSUE THREAD

**Issue by ghost** [AsgardEternal/Ubuntu-Ansible-Setup#11]

**Comment by PriceHiller** [comment]
This is going to require an integration to check for current player count. We don't want to kill a live server.

**Comment by PriceHiller** [comment]
Going to be working on this soon (probably tomorrow), after reviewing some things related to Squad servers it seems a regular restart schedule maintains stability. It seems Squad has a lot of issues with open threads and whatnot after around 24ish hours of continuous operation.

This is going to require querying the server via rcon and getting a player list then serializing that down into a player count (unless the rcon return also includes the exact player count).

I'm leaning to implementing this in Rust just so I don't have to package any other dependencies and can just pull a simple binary to handle the rcon querying. Rcon is a pretty old, standardized protocol so there's probably already Rust libs out there for Rcon.

If there are not we can fall back on ye-olde python/squadjs rcon libs that 100% exist to query, but we'll have to bundle more deps.
